import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import './globals.css';
import MuiProvider from '@/components/providers/mui-provider.component';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { VLibrasComponent } from '@/components/lib/vlibras.component';
import { BackToTop } from '@/components/layout/back-to-top.component';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="PT-BR"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <AppRouterCacheProvider>
        <body className="min-h-full flex flex-col">
          <MuiProvider>{children}</MuiProvider>
          <ToastContainer theme="colored" />
          <VLibrasComponent />
          <BackToTop />
        </body>
      </AppRouterCacheProvider>
    </html>
  );
}
