#!/bin/sh

branch=$(git rev-parse --abbrev-ref HEAD)

if ! echo "$branch" | grep -E "^(feature|fix|hotfix|release|bugfix|docs|refactor|test)/[a-z0-9._-]+$"; then
  echo "❌ Nome da branch inválido!"
  echo "Use: feature/, fix/, hotfix/, release/, bugfix/, docs/, refactor/, test/"
  exit 1
fi

npm run format